Bot.py

:fire: fix
:fire: fix
:fire: fix
:fire: fix
:fire: fix
:fire: fix
:fire: fix
:fire: fix
:fire: fix
:fire: fix
:fire: fix
:fire: fix

:fire: fix

---

plugins/MUN Identity/__init__.py

third hot fiya fix

---

plugins/MCWhitelist/mojang_api.py

properly handle no custom mc skin

---

plugins/TodayAtMun/Today.py
plugins/TodayAtMun/__init__.py

* Fixed !today later.
* New Command: !today nextfive - this command sends one embeded message to discord of five of the next significant dates from the MUN diary.
* removed unused import in __init__.py
* Some small changes aswell, embed colour, code block to single block, footer icon.

implements nextfive com, bug fixes, style changes

---

requirements.txt

* Upgrade discord.py to fix a breaking change that caused bots to crash repeatedly on startup

Upgrade discord.py

---

plugins/Vibe/__init__.py
plugins/Vibe/plugin.json

Replies with a cat bop gif. That's it.

Cat Bop (VIbe command)

---

plugins/Vibe/__init__.py

Updated link which works better with discord

Better GIF Link

---

plugins/Vibe/__init__.py

Added Vibing levels. 
Send help.

Final changes on this command(maybe lol).

---

plugins/WiseQuote/__init__.py
plugins/WiseQuote/plugin.json

The MUN CS Society discord server is not inspirational enough. We need to seed it with inspirational quotes.

feat/plugin: inspire us

---

plugins/Hewwo/__init__.py

Escape mentions

---

requirements.txt

Reverts MUNComputerScienceSociety/Automata#42
broke deploy https://github.com/MUNComputerScienceSociety/Automata/actions/runs/893584432

Revert "Bump aiohttp from 3.6.2 to 3.7.4"

---

plugins/FAQ/__init__.py
plugins/FAQ/plugin.json

Created some commands to answer some questions we always get asked. More could be added for different questions. ( ͡° ͜ʖ ͡°) lmk if I should change anything

added FAQ plugin v1

---

plugins/Ecoji/__init__.py
plugins/Ecoji/plugin.json

Fetches randomly generated emojis based on Jack Harrhy's **Ecoji** project.

Added new 'Ecoji' plugin

---

plugins/FAQ/__init__.py

fixed link and added new info about science electives

added new link and fixed science electives

---

plugins/Course/__init__.py
plugins/Course/bannerScraper.py
plugins/Course/calendarScraper.py
plugins/Course/peopleScraper.py
plugins/Course/plugin.json
plugins/Course/rmpScraper.py

I made a plugin!
You do "!course ####" and it shows the name of the course, its description from the calendar, whether or not anyone is teaching it this semester, who the profs are if there are any, and the Rate My Prof scores of those professors.

Added Course plugin

---

plugins/Course/bannerScraper.py
plugins/Course/plugin.json

Fixed banner caching

---

plugins/Uptime/__init__.py

Automata cant get any sleep

---

plugins/TodayAtMun/__init__.py

Fix exam command, update link to F21

---

mounted_plugins/DisDay/__init__.py
mounted_plugins/DisDay/plugin.json

**this plugin prints a popular event in history on the current date**
This is my initial work, and I expect to add more changes. Right now, the API randomly returns an event that happened in the past, but it returns the same event for a period of time. It doesn't change often. I will be adding more endpoints. 
I just wanted someone to have a look at my work and suggest any changes, and even provide their feedback on my idea. Is it even feasible, let alone cool?
I need to change the text format a little and correct the grammar, as the events are returned as present tense instead of past. 
I will tag Jack as I have been talking to him about plugin development, _and I know he is best kind_ :)
@jackharrhy

created 'disday' plugin to show

---

requirements.txt

Reverts MUNComputerScienceSociety/Automata#146

Revert "Bump httpx from 0.19.0 to 0.23.0"

---

plugins/MUN Identity/__init__.py

fix: only attempt verified related messages cleanup outside of DMChannel

---

.github/workflows/deploy.yml
docker-compose.yml

Fix container image deployment
